# This is a workflow to upload demo page

name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "master" branch
    push:
        branches: ['master']

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Set permissions
permissions:
    contents: read

# Cancel the previous job when running duplicate jobs
concurrency:
    group: 'pages'
    cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist

    deploy:
        needs: build

        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            id-token: write
            pages: write

        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
              id: deployment
